
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Feature.Navigation.Models
{
    /// <summary>
	/// IFooter interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Navigation/Footer</para>	
	/// <para>ID: 1d19c11b-ab08-463d-9a3a-56a65c8ad5e8</para>	
	/// </summary>
	[SitecoreType(TemplateId = IFooterConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IFooter : IGlassBase
	{
		/// <summary>
		/// Represents Copyright field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: b1e25f41-549a-4ae1-b5df-52359ec248b8</para>	
        /// <para>Section: Footer</para>
		/// </summary>
        [SitecoreField(IFooterConstants.Copyright_FieldId, SitecoreFieldType.SingleLineText, "Footer")]
        string Copyright { get; set; }
	}
	
	public static partial class IFooterConstants
	{
		public const string TemplateIdString = "1d19c11b-ab08-463d-9a3a-56a65c8ad5e8";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Footer";
		
        public static readonly ID Copyright = new ID("b1e25f41-549a-4ae1-b5df-52359ec248b8");
        public const string Copyright_FieldId = "{b1e25f41-549a-4ae1-b5df-52359ec248b8}";
        public const string Copyright_FieldName = "Copyright";
	}
	
	/// <summary>
	/// Footer class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Navigation/Footer</para>	
	/// <para>ID: 1d19c11b-ab08-463d-9a3a-56a65c8ad5e8</para>	
	/// </summary>
	public partial class Footer : GlassBase, IFooter
	{
        /// <summary>
		/// Represents Copyright field
		/// <para>Path: /sitecore/templates/Feature/Navigation/Footer/Footer/Copyright</para>	
		/// <para>ID: b1e25f41-549a-4ae1-b5df-52359ec248b8</para>	
		/// </summary>
        [SitecoreField(IFooterConstants.Copyright_FieldId, SitecoreFieldType.SingleLineText, "Footer")]
        public virtual string Copyright { get; set; }
	}

    /// <summary>
	/// IHeader interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Navigation/Header</para>	
	/// <para>ID: 84239d4f-c795-4239-a471-1096384c956c</para>	
	/// </summary>
	[SitecoreType(TemplateId = IHeaderConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IHeader : IGlassBase
	{
		/// <summary>
		/// Represents Login Page field
		/// <para>Field Type: tree</para>	
		/// <para>ID: 5285f77b-685d-44f3-bc8a-73c621d02fe2</para>	
        /// <para>Section: Header</para>
		/// </summary>
        [SitecoreField(IHeaderConstants.LoginPage_FieldId, SitecoreFieldType.File, "Header")]
        Guid LoginPage { get; set; }/// <summary>
		/// Represents Logo field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 591ac1ba-4d78-4373-b890-d7115e322336</para>	
        /// <para>Section: Header</para>
		/// </summary>
        [SitecoreField(IHeaderConstants.Logo_FieldId, SitecoreFieldType.SingleLineText, "Header")]
        string Logo { get; set; }
	}
	
	public static partial class IHeaderConstants
	{
		public const string TemplateIdString = "84239d4f-c795-4239-a471-1096384c956c";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Header";
		
        public static readonly ID LoginPage = new ID("5285f77b-685d-44f3-bc8a-73c621d02fe2");
        public const string LoginPage_FieldId = "{5285f77b-685d-44f3-bc8a-73c621d02fe2}";
        public const string LoginPage_FieldName = "Login Page";
        public static readonly ID Logo = new ID("591ac1ba-4d78-4373-b890-d7115e322336");
        public const string Logo_FieldId = "{591ac1ba-4d78-4373-b890-d7115e322336}";
        public const string Logo_FieldName = "Logo";
	}
	
	/// <summary>
	/// Header class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Navigation/Header</para>	
	/// <para>ID: 84239d4f-c795-4239-a471-1096384c956c</para>	
	/// </summary>
	public partial class Header : GlassBase, IHeader
	{
        /// <summary>
		/// Represents Login Page field
		/// <para>Path: /sitecore/templates/Feature/Navigation/Header/Header/Login Page</para>	
		/// <para>ID: 5285f77b-685d-44f3-bc8a-73c621d02fe2</para>	
		/// </summary>
        [SitecoreField(IHeaderConstants.LoginPage_FieldId, SitecoreFieldType.File, "Header")]
        public virtual Guid LoginPage { get; set; }/// <summary>
		/// Represents Logo field
		/// <para>Path: /sitecore/templates/Feature/Navigation/Header/Header/Logo</para>	
		/// <para>ID: 591ac1ba-4d78-4373-b890-d7115e322336</para>	
		/// </summary>
        [SitecoreField(IHeaderConstants.Logo_FieldId, SitecoreFieldType.SingleLineText, "Header")]
        public virtual string Logo { get; set; }
	}

}
