---
ID: "7631f23c-dcda-4d89-b179-3e10ba047b5d"
Parent: "d9db7d32-0808-4e13-a7b7-38b876e27eb4"
Template: "d9db7d32-0808-4e13-a7b7-38b876e27eb4"
Path: /sitecore/templates/Project/SCSDemo/Page Types/Event/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210816T214457Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "12af2a14-65b5-4bf9-b43a-40617d0dabe2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210816T214457Z
