
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Feature.Metadata.Models
{
    /// <summary>
	/// IMetadata interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Feature/Metadata/_Metadata</para>	
	/// <para>ID: 30b06829-8574-4839-80c8-e38c27002d3b</para>	
	/// </summary>
	[SitecoreType(TemplateId = IMetadataConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IMetadata : IGlassBase
	{
		/// <summary>
		/// Represents Page Title field
		/// <para>Field Type: Single-Line Text</para>	
		/// <para>ID: 3621108f-078f-4dee-9954-635c86673354</para>	
        /// <para>Section: Metadata</para>
		/// </summary>
        [SitecoreField(IMetadataConstants.PageTitle_FieldId, SitecoreFieldType.SingleLineText, "Metadata")]
        string PageTitle { get; set; }/// <summary>
		/// Represents SEO Keywords field
		/// <para>Field Type: Multi-Line Text</para>	
		/// <para>ID: fc10a5c5-5f18-477d-93ad-212be69427db</para>	
        /// <para>Section: Metadata</para>
		/// </summary>
        [SitecoreField(IMetadataConstants.SeoKeywords_FieldId, SitecoreFieldType.MultiLineText, "Metadata")]
        string SeoKeywords { get; set; }
	}
	
	public static partial class IMetadataConstants
	{
		public const string TemplateIdString = "30b06829-8574-4839-80c8-e38c27002d3b";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Metadata";
		
        public static readonly ID PageTitle = new ID("3621108f-078f-4dee-9954-635c86673354");
        public const string PageTitle_FieldId = "{3621108f-078f-4dee-9954-635c86673354}";
        public const string PageTitle_FieldName = "Page Title";
        public static readonly ID SeoKeywords = new ID("fc10a5c5-5f18-477d-93ad-212be69427db");
        public const string SeoKeywords_FieldId = "{fc10a5c5-5f18-477d-93ad-212be69427db}";
        public const string SeoKeywords_FieldName = "SEO Keywords";
	}
	
	/// <summary>
	/// Metadata class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Feature/Metadata/_Metadata</para>	
	/// <para>ID: 30b06829-8574-4839-80c8-e38c27002d3b</para>	
	/// </summary>
	public partial class Metadata : GlassBase, IMetadata
	{
        /// <summary>
		/// Represents Page Title field
		/// <para>Path: /sitecore/templates/Feature/Metadata/_Metadata/Metadata/Page Title</para>	
		/// <para>ID: 3621108f-078f-4dee-9954-635c86673354</para>	
		/// </summary>
        [SitecoreField(IMetadataConstants.PageTitle_FieldId, SitecoreFieldType.SingleLineText, "Metadata")]
        public virtual string PageTitle { get; set; }/// <summary>
		/// Represents SEO Keywords field
		/// <para>Path: /sitecore/templates/Feature/Metadata/_Metadata/Metadata/SEO Keywords</para>	
		/// <para>ID: fc10a5c5-5f18-477d-93ad-212be69427db</para>	
		/// </summary>
        [SitecoreField(IMetadataConstants.SeoKeywords_FieldId, SitecoreFieldType.MultiLineText, "Metadata")]
        public virtual string SeoKeywords { get; set; }
	}

}
