
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Leprechaun tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.CodeDom.Compiler;
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Sitecore.Foundation.ORM.Models;

namespace Sitecore.Project.SCSDemo.Models.PageTypes
{
    /// <summary>
	/// IArticle interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/Article</para>	
	/// <para>ID: f873ac77-5a1c-4d1a-9380-66fc93ece25d</para>	
	/// </summary>
	[SitecoreType(TemplateId = IArticleConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IArticle : global::Sitecore.Feature.Metadata.Models.IMetadata
	{
		
	}
	
	public static partial class IArticleConstants
	{
		public const string TemplateIdString = "f873ac77-5a1c-4d1a-9380-66fc93ece25d";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Article";
		
	}
	
	/// <summary>
	/// Article class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/Article</para>	
	/// <para>ID: f873ac77-5a1c-4d1a-9380-66fc93ece25d</para>	
	/// </summary>
	public partial class Article : global::Sitecore.Feature.Metadata.Models.Metadata, IArticle
	{
        
	}

    /// <summary>
	/// IEvent interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/Event</para>	
	/// <para>ID: d9db7d32-0808-4e13-a7b7-38b876e27eb4</para>	
	/// </summary>
	[SitecoreType(TemplateId = IEventConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface IEvent : global::Sitecore.Feature.Metadata.Models.IMetadata
	{
		
	}
	
	public static partial class IEventConstants
	{
		public const string TemplateIdString = "d9db7d32-0808-4e13-a7b7-38b876e27eb4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Event";
		
	}
	
	/// <summary>
	/// Event class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/Event</para>	
	/// <para>ID: d9db7d32-0808-4e13-a7b7-38b876e27eb4</para>	
	/// </summary>
	public partial class Event : global::Sitecore.Feature.Metadata.Models.Metadata, IEvent
	{
        
	}

    /// <summary>
	/// Itest interface generated based on sitecore item
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/test</para>	
	/// <para>ID: 94843591-961c-4263-8254-cf38e0d2db3a</para>	
	/// </summary>
	[SitecoreType(TemplateId = ItestConstants.TemplateIdString)]
	[GeneratedCode("Leprechaun", "2.0.0.0")]
	public partial interface Itest : IGlassBase
	{
		
	}
	
	public static partial class ItestConstants
	{
		public const string TemplateIdString = "94843591-961c-4263-8254-cf38e0d2db3a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "test";
		
	}
	
	/// <summary>
	/// test class generated based on sitecore item	
	/// <para>Path: /sitecore/templates/Project/SCSDemo/Page Types/test</para>	
	/// <para>ID: 94843591-961c-4263-8254-cf38e0d2db3a</para>	
	/// </summary>
	public partial class test : GlassBase, Itest
	{
        
	}

}
