---
ID: "4b68e71e-fafa-45fc-a8cb-4d4b8b3ea00d"
Parent: "77347359-ad25-4609-b008-bf785d77e92f"
Template: "77347359-ad25-4609-b008-bf785d77e92f"
Path: /sitecore/templates/Project/SUGDE/Event/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220423T190619Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c4d077f3-09d0-4034-b31f-0659a070af40"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220423T191122Z
    - ID: "f2034eec-c39a-4511-9f3c-c5fba7f689f4"
      Hint: Title
      Value: $name
